export const FILTER_BY_GROUPS = 'FILTER_BY_GROUPS';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_INCOMING = 'FILTER_INCOMING';
export const FILTER_OUTGOING = 'FILTER_OUTGOING';
