export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_GROUPS = 'GET_GROUPS';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const GET_CURRENT_CONTACT = 'GET_CURRENT_CONTACT';
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';